### ISSUE TITLE
interference with adi_variables

### ISSUE THREAD

**Issue by jools-r** [gocom/rah_flat#12]
Hi Jukka,

Just trying this new version and it works wonderfully. But it also cleaned out my adi_variables form though too, and from this follows two questions:

* Is there a way to make rah_flat ignore a form (e.g. adi_variables)? That used to be possible in an earlier version by adding form names to `rah_flat.config.xml` but the removal method seems to have changed since (If I've understood it correctly, rah_flat now drops the entire table and replaces it with the new items from the flat files?).
* Is there a way to have the adi_variables panel still functional? This was mentioned in Issue 3 with an earlier version of rah_flat. I think adi has since changed his own prefs system for v0.5 of adi_variables.

Thanks for your useful feedback :-) Jools

**Comment by gocom** [comment]
Realistically adi_variables shouldn't be using forms to store it's configuration.

As far as adding ignoring goes, it would be rather unintuitive since rah_flat doesn't protect templates in any other way, and it would be forced to leave behind trash forms with old code still active (as the templates in DB aren't removed when the file is); this could then also lead into security vulnerabilities as old code could leak into your templates due to it not getting removed where you think it is.

I would recommend to investing to alternative configuration changing tactic or updating adi_variables. For instance, Textpattern's preferences panel is fully extendable and new fields can be added there to store configuration.

I.e. the most minimalistic configuration storer plugin would require just couple lines of code:

```php
// Creates a new field to preferences if it doesn't already exist.

if (get_pref('abc_sitecfg_myfieldname', false) === false) {
    set_pref('abc_sitecfg_myfieldname', 'Default value', 'abc_sitecfg', PREF_ADVANCED, 'text_input', 80);
}

// Pass preferences to variables.

$variable = $prefs;
```

And you get sweet looking preference group in the Preferences panel and variables you can access in your page templates. Add more set statements to add more fields to fit your needs. The field labels can be localized with Textpacks:

```
#@language en-gb
abc_sitecfg => Preference group header
abc_sitecfg_myfieldname => Field label
```

And you can call them like so in your templates:

```html
<txp:variable name="abc_sitecfg_myfieldname" />
```
