### ISSUE TITLE
Not writing to disk

### ISSUE THREAD

**Issue by Manaus** [gocom/rah_flat#18]
Hello,  
I installed rah_flat on a local copy of Txp 457, using Mamp. Still I can't see any directory created, I'm using `../templates` or `../../src/templates` as destination path, and tried also to invoke the process using the secure key, which rendered `{success: true}`. 
Tried also do create the folder myself, to no avail. 
Thanks

**Comment by c2mrdale** [comment]
Works for me… make sure your install is set to testing and not live

On January 20, 2016 at 3:56:21 AM, Manaus (notifications@github.com) wrote:

Hello,

I installed rah_flat on a local copy of Txp 457, using Mamp Still I can't see any directory created, I'm using /templates or //src/templates as destination path, and tried also to invoke the process using the secure key, which rendered {success: true}
Tried also do create the folder myself, to no avail
Thanks

—
Reply to this email directly or view it on GitHub.

-- 
Dale Chapman
Sent with Airmail

**Comment by Manaus** [comment]
Thanks Dale,  
tried out every possible combination {debug, test, live+key}, but nothing seems to work...

**Comment by jools-r** [comment]
Manaus, rah_flat is a one-way street. It **doesn't write to disk**, it only imports from flat files to the database. In the process **it overwrites all forms and page templates** that were in the DB, so save your pages and forms first, or they will be gone! (see below)

Create your own `templates` directory where you want to have it, then directories for `pages` and `forms` (styles, sections and prefs too if you want) and place your own page and form templates in those folders. See the [example templates folder](https://github.com/gocom/rah_flat/tree/master/templates) for examples of the necessary filenaming conventions and file contents.

Then install the plugin (or use composer) and go to `Admin > Settings` to set the directory path to match the path of your templates folder. It is relative to the `/textpattern` directory, so if you have your templates directory in your base directory next to your textpattern directory, it will be `../templates`. Jukka's default path is  `../../templates` which puts the templates folder one level beneath the public root so that it's not accessible from the web. If you can't do that with your server setup and would rather not that people can look in the folder, you can protect the directory from prying eyes as shown [here](https://github.com/textpattern/textpattern-com-website/blob/274d3483d632fe59c7ab51eb87ba862f38dba3d9/public/templates/.htaccess).

Your site needs to be in testing mode, and if you've got things set up correctly, you won't see the pages and forms panels under the presentation menu. It essentially loads all the forms and page templates with every page load (you'll see a high DB count in the tag trace), so remember to switch the status back to live when you launch your site.

Maniqui has written [a python script to export all your forms and pages](https://github.com/gocom/rah_flat/issues/15), and if you have python set up (or install it), you can use that to export all your existing forms and pages at once.

I hope that clarifies things.

**Comment by Manaus** [comment]
Oh now working, thanks mate!
