### ISSUE TITLE
variable / prefs clarification needed (in docs perhaps)

### ISSUE THREAD

**Issue by jools-r** [gocom/rah_flat#24]
Maybe this is just me? ;-) but I was confused by the difference between prefs and variables. As far as I can tell:

**Variables** (= hard-coded by developer)

- Non-editable in the txp admin
- Always overwritten by the value in the flat file
- Hence: the value **must** be specified in the flat file

**Prefs** (= user-editable for admin users with appropriate privileges)

- Editable via the txp admin area in the Preferences > rah_flat_variables panel
- Only created but not overwritten by the flat file
- Flat file can be blank

Correct?

**Comment by NicolasGraph** [comment]
@jools-r, I took a try and here is how it seems to works:

**Variables**
- Created and updated from flat files while the related `/variables` folder exists in the provided templates path;
- shown as the `rah_flat_variables` prefs group and updated from the admin side when the folder is deleted.

**Prefs**
- Always shown;
- updated from the flat files while the `/prefs` folder exists;
- updated via the admin otherwise.
- accept JSON files or plain text files (may probably be empty…).
